#!/usr/bin/env bash
#set -x
# ---- |EXT ----
USER_NAME=$1
USER_EMAIL=$2
VARSET_EXT=$2
# ---- |DEFAULT ----
USER_NAME=${USER_NAME:-github-ajm6}
USER_EMAIL=${USER_EMAIL:-github-ajm6@github.com}
# ---- |OVERRIDE ----
source .properd/VARSET
test -n "$VARSET_EXT" && source $VARSET_EXT

# ---- |MAIN ----

git config user.email $USER_EMAIL
git config user.name $USER_NAME

