#!/usr/bin/env bash
#set -x
# ---- |EXT ----
NAME=${1:-dev}
VARSET_EXT=$2
# ---- |DEFAULT ----
MODULE_DIR=modules/$NAME
# ---- |OVERRIDE ----
source .properd/VARSET
test -n "$VARSET_EXT" && source $VARSET_EXT

# ---- |MAIN ----
mkdir -p $MODULE_DIR
cp .template/terragrunt.hcl  $MODULE_DIR
cp .template/backend.tf  $MODULE_DIR
cp .template/main.tf  $MODULE_DIR
cp .template/vars.tf  $MODULE_DIR
cat .template/terraform.tfvars | WID=$(uuidgen) envsubst  > $MODULE_DIR/terraform.tfvars
