#!/usr/bin/env bash
#set -x
# ---- |EXT ----
NAME=${1:-dev}
VARSET_EXT=$2
# ---- |DEFAULT ----
MODULE_DIR=modules/$NAME
# ---- |OVERRIDE ----
source .properd/VARSET
test -n "$VARSET_EXT" && source $VARSET_EXT

# ---- |MAIN ----
echo "Planning: $NAME"
cd $MODULE_DIR  &&  terragrunt plan
