name: base

on: [push, pull_request]

jobs:
  check_sizes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get folder sizes
        id: folder_sizes
        run: |
          find . -maxdepth 1 -type d -not -name '.' -print0 | while IFS= read -r -d $'\0' folder; do
            du -sh "$folder" | awk '{print $1, $2}'
          done

